version: '3.8'
services:
  app:
    image: todo-app-with-utils
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy  # db가 건강 상태를 만족해야 시작
    networks:
      - todo_app-network
    command: ["/app/wait-for-it.sh", "db:3306", "--timeout=30", "--strict", "--", "java", "-jar", "app.jar"]

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo_app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  todo_app-network:
    external: true
