version: '3.8'
services:
  app:
    image: todo-app-with-utils  # 새로운 이미지 이름
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - todo_app-network
    command: ["/app/wait-for-it.sh", "db:3306", "--timeout=30", "--strict", "--", "java", "-jar", "app.jar"]

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo_app-network

networks:
  todo_app-network:
    external: true
